apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: review-and-rating-svc
  backstage.io/kubernetes-id: review-and-rating-svc
images:
  - name: to-be-replaced
    newName: ghcr.io/nicpym/review-and-rating-svc
    newTag: v0.0.1
